# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c83b37819848b4db204ddb86c1091e9bf31bbca988d59dbb5256240fc59d6f359092b839adbeee1abf06e5ae2bb56d4e0663595f6da3196fac078f429de3ff3a

test:
  secret_key_base: 75a312a735ef996e8237feece2ec00e2c5539ffdb56a981e0969e8d98410b89debdb57794442b7923c65d5dc68488ebc7643420e2382366c765eae3bcfab7e9d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
